apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
spec:
  serviceMonitorSelector:
    matchLabels:
      team: boracho
  resources:
    requests:
      memory: 400Mi
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: boracho
  labels:
    team: boracho
spec:
  selector:
    matchLabels:
      app: test-app
  endpoints:
  - port: metrics
